import type { NextPage } from 'next'
import Head from 'next/head'
import { Viewer } from '@bytemd/react'
import pluginGfm from '@bytemd/plugin-gfm'
import highlight from '@bytemd/plugin-highlight'
import styles from '../styles/Home.module.css'
import { useMemo, useState } from 'react'



const Home: NextPage = () => {
    const [value, setValue] = useState(
        "# 测试发布文章\n\n\n```js\nconst a = 1233;\nconst func = () => {\n    return 123;\n}\n```\n\n## list\n1. - item1\n2. - item2\n3. - item3\n\n\n| Heading | aaaaaaaaaa | baaaaaaaaa |\n| --- | --- | --- |\n| 1 | 2 | 3 |\n"
    );
  const plugins = useMemo(() => [pluginGfm(),highlight()], [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Viewer value="abc" /> */}

      <Viewer
        value={value}
        plugins={plugins}
      />
    </div>
  )
}

export default Home
